databases:
  - name: spotteraidb         
    plan: free
    databaseName: spotterai    #
    user: spotterai_user 

services:
  - type: web
    plan: free
    name: spotterai-web     
    runtime: python
    buildCommand: "./build.sh" 
    startCommand: "gunicorn spotterAi.wsgi:application" 
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spotteraidb     
          property: connectionString
      - key: SECRET_KEY
        generateValue: true     
      - key: ORS_API_KEY       
        value: "5b3ce3597851110001cf624892f9044c9cba4d648aba9a1e13ba45c4" 
      - key: WEB_CONCURRENCY
        value: 4               
      - key: PYTHON_VERSION     
        value: 3.11.7           
