# Generated by Django 4.2.20 on 2025-04-02 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trip', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_location', models.CharField(max_length=255)),
                ('current_coordinates', models.CharField(default='0.0,0.0', max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_coordinates', models.CharField(default='0.0,0.0', max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_coordinates', models.CharField(default='0.0,0.0', max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours used from 70hr/8day cycle')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimatedEndDate', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('rest', '10-Hour Rest'), ('break', '30-Minute Break'), ('fuel', 'Fueling'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=50)),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('elapsed_trip_time', models.FloatField(help_text='Hours elapsed since trip start')),
                ('planned_arrival_time', models.DateTimeField()),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tracking.trip')),
            ],
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='tracking.trip')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('driving', 'Driving'), ('on_duty', 'On Duty Not Driving'), ('sleeper_berth', 'Sleeper Berth'), ('off_duty', 'Off Duty')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='tracking.trip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
